name: Deploy on EC2 staging server

on:
  push:
    branches: [main]

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.STAGING_TARGET_DIR }}

      - name: Start or Restart Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Done code"
            # cd ${{ secrets.STAGING_TARGET_DIR }}
            # source .venv/bin/activate
            # pip install -r requirements.txt
            # python manage.py makemigrations
            # python manage.py migrate
            # pm2 restart 9
